[package]
name = "diorama_raytracing"
version = "0.1.0"
edition = "2021"

[dependencies]
raylib = "5.0"
rand = "0.8"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[[bin]]
name = "diorama"
path = "src/main.rs"